[package]
name = "fin-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
rand = "0.8.5"
rust_decimal = "1.26"
rust_decimal_macros = "1.26"
plotters = "0.3.4"
rayon = "1.5.3"